### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by firmai** [jtmorgan/social-media-traffic-reports#1]
Hey! Super cool analysis, is this something anyone can just replicate, I have noticed that you have added fake data for testing, does this mean that the real data can't be obtained?

**Comment by jtmorgan** [comment]
hey there. No, unfortunately this relies on access to internal Wikimedia Foundation traffic logs. But if you're interested in learning more (and perhaps there's a way forward), ping @geohci who's currently running the reports, as I no longer work at WMF.

**Comment by geohci** [comment]
Thanks for the question @firmai and letting me know @jtmorgan!

As jtmorgan noted, the data is generated from internal traffic logs that we apply privacy filtering on before releasing in this public format. If there's more specific questions, I can try to address them, but right now we only grant access to the internal logs through our formal collaborations program (https://www.mediawiki.org/wiki/Wikimedia_Research/Formal_collaborations).

**Comment by firmai** [comment]
Okay thats good thanks for pointing me in the right direction :)
